name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  ci:
    uses: yohn-jp/.github/.github/workflows/typescript-cli-ci.yml@9962f9262e333e4d3b14c5d5fe13a0b012c2d0bb
    with:
      working-directory: .
      node-version: "22"
      conformance-script: "test:package"
