name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  ci:
    uses: yohn-jp/.github/.github/workflows/typescript-cli-ci.yml@4fb520dcfc63f386a2e33d6c0a74f251f8dc9bdb
    with:
      working-directory: .
      node-version: "22"
      conformance-script: "test:package"
