name: Governance

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  governance:
    permissions:
      contents: read
      pull-requests: write
    uses: yohn-jp/.github/.github/workflows/pr-governance.yml@4fb520dcfc63f386a2e33d6c0a74f251f8dc9bdb
