name: Issue Governance

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  contents: read
  issues: write

jobs:
  governance:
    permissions:
      contents: read
      issues: write
    uses: yohn-jp/.github/.github/workflows/issue-governance.yml@4fb520dcfc63f386a2e33d6c0a74f251f8dc9bdb
