name: Issue Governance

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  contents: read
  issues: write

jobs:
  governance:
    permissions:
      contents: read
      issues: write
    uses: yohn-jp/.github/.github/workflows/issue-governance.yml@9962f9262e333e4d3b14c5d5fe13a0b012c2d0bb
